title: "Travis A. Lisk"
email: arduino@liskfamily.com
description: >- # this means to ignore newlines until "baseurl:"
  Testing out with GitHub Pages to see what I can do
baseurl: "/" 
url: "https://Arduino-TAL.github.io" 
twitter_username: LiskCoop
github_username:  Arduino-TAL

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
